-- MySQL Script generated by MySQL Workbench
-- Sat Apr 26 10:41:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pantry_planner_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pantry_planner_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pantry_planner_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pantry_planner_db` ;

-- -----------------------------------------------------
-- Table `pantry_planner_db`.`alembic_version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pantry_planner_db`.`alembic_version` (
  `version_num` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`version_num`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pantry_planner_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pantry_planner_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pantry_planner_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pantry_planner_db`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `brand` VARCHAR(255) NOT NULL,
  `price` DOUBLE NOT NULL,
  `household_qty` DOUBLE NOT NULL,
  `household_qty_threshold` DOUBLE NOT NULL,
  `qty_type` VARCHAR(255) NOT NULL,
  `purchase_qty` DOUBLE NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `product_id` VARCHAR(255) NOT NULL,
  `purchase_location` VARCHAR(255) NOT NULL,
  `location_id` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `pantry_planner_db`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pantry_planner_db`.`grocery_lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pantry_planner_db`.`grocery_lists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `product_purchased` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `grocery_lists_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `pantry_planner_db`.`products` (`id`),
  CONSTRAINT `grocery_lists_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `pantry_planner_db`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
