"""Update household_qty, household_qty_threshold, purchase_qty to Double

Revision ID: 32cc71802d3d
Revises: 97150cbc69f4
Create Date: 2025-04-22 22:44:20.712111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32cc71802d3d'
down_revision = '97150cbc69f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('household_qty',
               existing_type=mysql.INTEGER(),
               type_=sa.Double(),
               existing_nullable=False)
        batch_op.alter_column('household_qty_threshold',
               existing_type=mysql.INTEGER(),
               type_=sa.Double(),
               existing_nullable=False)
        batch_op.alter_column('purchase_qty',
               existing_type=mysql.INTEGER(),
               type_=sa.Double(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('purchase_qty',
               existing_type=sa.Double(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('household_qty_threshold',
               existing_type=sa.Double(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('household_qty',
               existing_type=sa.Double(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
