"""Add products table

Revision ID: 97150cbc69f4
Revises: 361d7d3e7562
Create Date: 2025-04-22 22:10:01.665049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97150cbc69f4'
down_revision = '361d7d3e7562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Double(), nullable=False),
    sa.Column('household_qty', sa.Integer(), nullable=False),
    sa.Column('household_qty_threshold', sa.Integer(), nullable=False),
    sa.Column('qty_type', sa.String(length=255), nullable=False),
    sa.Column('purchase_qty', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('purchase_location', sa.String(length=255), nullable=False),
    sa.Column('location_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
